[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rse-ci-cd-project"
dependencies = [
    "numba>=0.61.0",
    "pint>=0.24",
    "numpy>=2.0.0",
]
license = {text = "GPL-3.0-or-later"}
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
packages = ["src"]

[tool.setuptools_scm]
local_scheme = "no-local-version"
